modLoader="javafml"
loaderVersion="[41,)"
license="GNU GPL 3.0"
issueTrackerURL="https://github.Lodedm/RecraftorsMC/chests-are-chests/issues"
[[mods]]
modId="loded"
version="${version}"
displayName="Loded"
displayURL="https://modrinth.com/mod/loded"
logoFile="icon.png"
authors="Nerjal Nosk, Recraftors Team"
displayTest="IGNORE_SERVER_VERSION"
description='''
Allows to copy lodestone compasses
'''
[[dependencies.loded]]
   modId="forge"
   mandatory=true
   versionRange="[41,)"
   ordering="NONE"
   side="SERVER"
[[dependencies.loded]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19)"
   ordering="NONE"
   side="SERVER"
